services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: finx-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P \"$$MSSQL_SA_PASSWORD\" -Q \"SELECT 1\" >/dev/null || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 20s

  finx-api:
    build:
      context: .
      dockerfile: Finx.Api/Dockerfile
    container_name: finx-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=Finx;User ID=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;Encrypt=False;"
    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
